spring:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/postgresTest
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      
 




